print ("             Black Scholes for European Options")
corp = input("Call, Put, or Vol? ")
if corp == "Call":
    underpx = input("Underlying Price = ")
    xpx = input("Strike Price = ")
    intrt = input("Interest Rate = ")
    dte = input("Days to Expiration = ")
    #vol = input("Volatility = ")
    cpx = input("Call Price = ")
    #ppx = input("Put Price = ")
    import mibian
    c=mibian.BS([underpx, xpx, intrt, dte], callPrice=cpx)
    #print ("Call Price ",c.callPrice)
    print ("Put Price ", c.putPrice)
    print ("Call Delta ", c.callDelta)
    print ("Put Delta ", c.putDelta)
    print ("Call Theta ", c.callTheta)
    print ("Put Theta ", c.putTheta)
    print ("Call Rho ", c.callRho)
    print ("Put Rho ", c.putRho)
    print ("Vega ", c.vega)
    print ("Gamma ", c.gamma)
elif corp == "Put":
    underpx = input("Underlying Price = ")
    xpx = input("Strike Price = ")
    intrt = input("Interest Rate = ")
    dte = input("Days to Expiration = ")
    #vol = input("Volatility = ")
    #cpx = input("Call Price = ")
    ppx = input("Put Price = ")
    import mibian
    c=mibian.BS([underpx, xpx, intrt, dte], putPrice=ppx)
    print ("Call Price ",c.callPrice)
    #print ("Put Price ", c.putPrice)
    print ("Call Delta ", c.callDelta)
    print ("Put Delta ", c.putDelta)
    print ("Call Theta ", c.callTheta)
    print ("Put Theta ", c.putTheta)
    print ("Call Rho ", c.callRho)
    print ("Put Rho ", c.putRho)
    print ("Vega ", c.vega)
    print ("Gamma ", c.gamma)
else:
    #corp == Vol
    underpx = input("Underlying Price = ")
    xpx = input("Strike Price = ")
    intrt = input("Interest Rate = ")
    dte = input("Days to Expiration = ")
    vol = input("Volatility = ")
    #cpx = input("Call Price = ")
    #ppx = input("Put Price = ")
    import mibian
    c=mibian.BS([underpx, xpx, intrt, dte], volatility=vol)
    print ("Call Price ",c.callPrice)
    print ("Put Price ", c.putPrice)
    print ("Call Delta ", c.callDelta)
    print ("Put Delta ", c.putDelta)
    print ("Call Theta ", c.callTheta)
    print ("Put Theta ", c.putTheta)
    print ("Call Rho ", c.callRho)
    print ("Put Rho ", c.putRho)
    print ("Vega ", c.vega)
    print ("Gamma ", c.gamma)
